### ISSUE TITLE
Request for license on this repository.

### ISSUE THREAD

**Issue by sunayana** [ISI-MIP/isimip-client#1]
Would it be possible to put a permissible license on the code in this repository, e.g MIT?
And also update the dependency to requests to 2.28. 
Thank you very much.

**Comment by jochenklar** [comment]
Hi @sunayana , this was an oversight, the code is available under the MIT license, I added the LICENSE file. (And updated `requests`.)

**Comment by sunayana** [comment]
Thank you very much @jochenklar !
