### ISSUE TITLE
When job is not started for a long time, maximum recursion depth can be reached when using polling

### ISSUE THREAD

**Issue by jensdebruijn** [ISI-MIP/isimip-client#2]
The poll method is build using recursive programming, so can reach maximum recursion depth when job is not finished or started for a long time. https://github.com/ISI-MIP/isimip-client/blob/e00699d8fe7d0553c99f78581376773ab91f8cfb/isimip_client/client.py#L218

     RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by jochenklar** [comment]
Hi @jensdebruijn , thanks for reporting! It should be fixed now.
