### ISSUE TITLE
tree request?

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isimip-client#6]
Hi @jochenklar, I was trying out the "tree" search feature of the datasets.ipynb notebook and noted the following does not return any results:
`client.datasets(tree='ISIMIP3b/InputData/climate/atmosphere/global/daily/ssp370/gfdl-esm4/r1i1p1f1/w5e5/pr')`
In fact, I spent a few minutes trying out variations around that pattern and that did not help either. A bug or an API change? Perhaps the notebook should be updated? Best wishes

**Comment by jochenklar** [comment]
Hi @perrette thanks for reporting! The example is just wrong, it should be `ISIMIP3b/InputData/climate/atmosphere/gfdl-esm4/ssp370/pr/`, I need to fix this. I need to work on the client soon anyway. Note that the `tree` is not the same as the `path`, it is a different hierarchy we use in the sidebar on https://data.isimip.org/search/.

**Comment by perrette** [comment]
Thanks!
